name: Setup

inputs:
  python-version:
    description: 'Python version'
    required: true
    default: '3.10.12'

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        pip install -r requirements.txt
