name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'  # Spécifie la version de Python à utiliser

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Installe les dépendances listées dans requirements.txt
          pip install coverage  # Assure-toi que coverage est installé

      - name: Run tests with coverage
        run: |
          coverage run -m pytest  # Exécute pytest avec coverage
          coverage xml  # Génère le fichier coverage.xml

      - name: Coverage report
        uses: orgoro/coverage@v3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          coverageFile: coverage.xml
          thresholdAll: "0.8"

  release:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: major
          use_github_release_notes: true
